### ISSUE TITLE
It's not possible to set send rotation or mirroring

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc-android-sdk#3]
This is implemented in OpenWebRTC but needs to be implemented in a way that makes sense in the SDK.

**Comment by carterbryden** [comment]
Seconded, there was an issue opened and closed in the openwebrtc-examples repo that dealt with this, though mainly focused on iOS. It didn't seem to come to any useful conclusion as far as I could tell. Still not sure how to handle rotation using the sdk.

**Comment by stefanalund** [comment]
As @Rugvip points out, this would likely be a pretty simple add-on to the SDK. @carterbryden any chance you would be interested in having a crack at it?

**Comment by carterbryden** [comment]
We're going to take a look at it and see if we can come up with something
