### ISSUE TITLE
could you tell me some thing about the openwebrtc server?

### ISSUE THREAD

**Issue by wudimeicom** [EricssonResearch/openwebrtc-android-sdk#7]
could you tell me some thing about the openwebrtc server?

// must use 'url' here since Firefox doesn't understand 'urls'
var configuration = {
  "iceServers": [
  {
    "url": "stun:mmt-stun.verkstad.net"
  },
  {
    "url": "turn:mmt-turn.verkstad.net",
    "username": "webrtc",
    "credential": "secret"
  }
  ]
};

is there any open source project  like the "mmt-turn.verkstad.net" ?

thank you for you reply.

best regards

Yang Qing-rong

**Comment by Rugvip** [comment]
If you're referring to public stun servers, then here's a list: https://gist.github.com/zziuni/3741933

If you want to host your own stun server, we've used coturn iirc: https://code.google.com/p/coturn

**Comment by wudimeicom** [comment]
hello , Rugvip
 thank you very much !
